# Generated by Django 4.2.29 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Reports", max_length=100)),
            ],
            options={
                "verbose_name": "Reports",
                "verbose_name_plural": "Reports",
            },
        ),
    ]
