# Generated by Django 4.2.29 on 2026-03-16 20:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('billing_address1', models.CharField(max_length=255)),
                ('billing_address2', models.CharField(blank=True, max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('billing_term', models.PositiveSmallIntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (9, '9 Months'), (12, '12 Months')], default=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Primary Service', max_length=255)),
                ('service_address1', models.CharField(max_length=255)),
                ('service_address2', models.CharField(blank=True, max_length=255)),
                ('activation_date', models.DateField()),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.customer')),
            ],
            options={
                'ordering': ['customer__name', 'service_name', 'id'],
            },
        ),
    ]
