# Generated by Django 4.2.29 on 2026-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
