# Generated by Django 4.2.29 on 2026-03-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_first_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
