# Generated by Django 4.2.29 on 2026-03-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_service_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='Alarm Monitoring Service', max_length=255),
        ),
    ]
