# Generated by Django 4.2.29 on 2026-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_service_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auto_ach',
            field=models.BooleanField(default=False),
        ),
    ]
